/** Research-only inventory transcribed from the user's 2026-09-26 brief.
 * These are 25 candidate windows, NOT 25 verified laws, affected addresses,
 * searchable pages, or recalculated OpportunityScore records.
 */
export type TriggerType =
  | "DEADLINE"
  | "PERIODIC_INSPECTION"
  | "PERFORMANCE_THRESHOLD"
  | "PUBLIC_INVENTORY_REPLACEMENT"
  | "TRANSACTION_EVENT_TRIGGER";

export type ResearchWindow = {
  rank: number;
  slug: string;
  name: string;
  geography: string;
  triggerType: TriggerType;
  triggerWindow: string;
  serviceIntents: string;
  researchScore: number;
  tier: "A" | "B";
  existingRegulationSlug?: string;
  evidenceStatus: "UNVERIFIED";
  publicationStatus: "RESEARCH_ONLY";
  provenance: "USER_BRIEF_2026_09_26";
  lastPrimarySourceVerifiedAt: null;
};

export const regulatoryWindowResearch: ResearchWindow[] = [
  {
    "rank": 1,
    "slug": "cape-cod-septic-title-5",
    "name": "Cape Cod Septic / Title 5",
    "geography": "MA / Cape Cod",
    "triggerType": "DEADLINE",
    "triggerWindow": "Nitrogen-sensitive areas; no universal parcel deadline, watershed pathway varies",
    "serviceIntents": "Septic; engineering; excavation; sewer",
    "researchScore": 98,
    "tier": "A",
    "existingRegulationSlug": "massachusetts-title-5-septic",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 2,
    "slug": "florida-enr-septic-upgrade",
    "name": "Florida ENR Septic Upgrade",
    "geography": "FL / Indian River Lagoon",
    "triggerType": "DEADLINE",
    "triggerWindow": "July 1, 2030 statutory target; 2026 text limits residential scope to 10 acres or less; sewer and boundary conditional",
    "serviceIntents": "Sewer connection; ENR septic; engineering",
    "researchScore": 98,
    "tier": "A",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 3,
    "slug": "illinois-lead-service-lines",
    "name": "Illinois Lead Service Lines",
    "geography": "IL / Chicago metro",
    "triggerType": "PUBLIC_INVENTORY_REPLACEMENT",
    "triggerWindow": "Utility-side replacement program; 2020 statewide counts are historical; parcel data and owner payment unproven",
    "serviceIntents": "Plumbing; excavation; trenchless; restoration",
    "researchScore": 97,
    "tier": "A",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 4,
    "slug": "florida-condo-milestone-repair",
    "name": "Florida Condo Milestone Repair",
    "geography": "FL / coastal condos",
    "triggerType": "PERIODIC_INSPECTION",
    "triggerWindow": "Building-age inspection and recurring cycle",
    "serviceIntents": "Engineering; concrete; structural repair",
    "researchScore": 97,
    "tier": "A",
    "existingRegulationSlug": "florida-condo-milestone-inspections",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 5,
    "slug": "nyc-local-law-97-retrofit",
    "name": "NYC Local Law 97 Retrofit",
    "geography": "NYC",
    "triggerType": "PERFORMANCE_THRESHOLD",
    "triggerWindow": "2030 emissions limits",
    "serviceIntents": "HVAC; electrification; controls; engineering",
    "researchScore": 96,
    "tier": "A",
    "existingRegulationSlug": "nyc-local-law-97",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 6,
    "slug": "nyc-facade-local-law-11",
    "name": "NYC Façade / Local Law 11",
    "geography": "NYC",
    "triggerType": "PERIODIC_INSPECTION",
    "triggerWindow": "Cycle 10, 2025–2030",
    "serviceIntents": "Inspection; façade restoration",
    "researchScore": 96,
    "tier": "A",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 7,
    "slug": "oregon-building-performance-standard",
    "name": "Oregon Building Performance Standard",
    "geography": "OR",
    "triggerType": "PERFORMANCE_THRESHOLD",
    "triggerWindow": "Building-size tiers in 2028, 2029 and 2030",
    "serviceIntents": "Audit; HVAC; controls; retrofit",
    "researchScore": 95,
    "tier": "A",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 8,
    "slug": "washington-clean-buildings",
    "name": "Washington Clean Buildings",
    "geography": "WA",
    "triggerType": "PERFORMANCE_THRESHOLD",
    "triggerWindow": "User-reported 2026, 2027 and 2028 tiers; 2026 date needs historical treatment",
    "serviceIntents": "Energy professional; HVAC; controls; retrofit",
    "researchScore": 95,
    "tier": "A",
    "existingRegulationSlug": "washington-clean-buildings",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 9,
    "slug": "boston-berdo-2030",
    "name": "Boston BERDO 2030",
    "geography": "Boston, MA",
    "triggerType": "PERFORMANCE_THRESHOLD",
    "triggerWindow": "Smaller covered buildings enter emissions limits in 2030",
    "serviceIntents": "Electrification; HVAC; envelope",
    "researchScore": 95,
    "tier": "A",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 10,
    "slug": "seattle-beps",
    "name": "Seattle BEPS",
    "geography": "Seattle, WA",
    "triggerType": "PERFORMANCE_THRESHOLD",
    "triggerWindow": "Reporting 2027–2030; performance targets 2031+",
    "serviceIntents": "Engineering; energy retrofit",
    "researchScore": 94,
    "tier": "A",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 11,
    "slug": "nyc-parking-garage-inspection",
    "name": "NYC Parking Garage Inspection",
    "geography": "NYC",
    "triggerType": "PERIODIC_INSPECTION",
    "triggerWindow": "User-reported subcycle 1C in 2026–2027",
    "serviceIntents": "Engineering; concrete; structural repair",
    "researchScore": 94,
    "tier": "A",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 12,
    "slug": "new-jersey-rental-lead-paint",
    "name": "NJ Rental Lead Paint",
    "geography": "NJ",
    "triggerType": "TRANSACTION_EVENT_TRIGGER",
    "triggerWindow": "Tenant turnover or recurring inspection",
    "serviceIntents": "Inspection; lead remediation",
    "researchScore": 93,
    "tier": "A",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 13,
    "slug": "massachusetts-lead-service-lines",
    "name": "Massachusetts Lead Service Lines",
    "geography": "MA",
    "triggerType": "PUBLIC_INVENTORY_REPLACEMENT",
    "triggerWindow": "User-reported replacement start in November 2027",
    "serviceIntents": "Plumbing; excavation; restoration",
    "researchScore": 93,
    "tier": "A",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 14,
    "slug": "pennsylvania-lead-service-lines",
    "name": "Pennsylvania Lead Service Lines",
    "geography": "PA",
    "triggerType": "PUBLIC_INVENTORY_REPLACEMENT",
    "triggerWindow": "User-reported baseline inventory in November 2027",
    "serviceIntents": "Plumbing; excavation; restoration",
    "researchScore": 92,
    "tier": "A",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 15,
    "slug": "philadelphia-building-tune-ups",
    "name": "Philadelphia Building Tune-Ups",
    "geography": "Philadelphia, PA",
    "triggerType": "PERIODIC_INSPECTION",
    "triggerWindow": "Staged 2026+ deadlines",
    "serviceIntents": "Tune-up; HVAC; controls",
    "researchScore": 92,
    "tier": "A",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 16,
    "slug": "hawaii-cesspool-conversion",
    "name": "Hawaii Cesspool Conversion",
    "geography": "HI",
    "triggerType": "DEADLINE",
    "triggerWindow": "Statewide conversion requirement; exact property pathway unverified",
    "serviceIntents": "Septic; improved wastewater system; sewer",
    "researchScore": 91,
    "tier": "B",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 17,
    "slug": "california-wildfire-hardening",
    "name": "California Wildfire Hardening",
    "geography": "CA fire zones",
    "triggerType": "TRANSACTION_EVENT_TRIGGER",
    "triggerWindow": "Insurance, disclosure and mitigation triggers; geography unverified",
    "serviceIntents": "Roof; vents; defensible space; windows",
    "researchScore": 91,
    "tier": "B",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 18,
    "slug": "la-soft-story-retrofit",
    "name": "LA Soft-Story Retrofit",
    "geography": "Los Angeles, CA",
    "triggerType": "DEADLINE",
    "triggerWindow": "Order-to-comply deadlines vary by building",
    "serviceIntents": "Engineering; seismic retrofit",
    "researchScore": 90,
    "tier": "B",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 19,
    "slug": "florida-sirs",
    "name": "Florida SIRS",
    "geography": "FL / condos",
    "triggerType": "PERIODIC_INSPECTION",
    "triggerWindow": "Reserve study and funded work; building-specific scope",
    "serviceIntents": "Roof; waterproofing; electrical; structural repair",
    "researchScore": 90,
    "tier": "B",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 20,
    "slug": "wisconsin-lead-line-replacement",
    "name": "Wisconsin Lead Line Replacement",
    "geography": "WI",
    "triggerType": "PUBLIC_INVENTORY_REPLACEMENT",
    "triggerWindow": "Funded replacement program; property obligations unverified",
    "serviceIntents": "Plumbing; excavation",
    "researchScore": 89,
    "tier": "B",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 21,
    "slug": "massachusetts-large-building-energy",
    "name": "Massachusetts Large Building Energy",
    "geography": "MA",
    "triggerType": "PERFORMANCE_THRESHOLD",
    "triggerWindow": "Annual reporting universe; physical-work trigger unverified",
    "serviceIntents": "Energy audit; consulting",
    "researchScore": 88,
    "tier": "B",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 22,
    "slug": "virginia-chesapeake-septic",
    "name": "Virginia Chesapeake Septic",
    "geography": "VA / Chesapeake Bay areas",
    "triggerType": "PERIODIC_INSPECTION",
    "triggerWindow": "User-reported five-year pump-out cycle",
    "serviceIntents": "Recurring septic service",
    "researchScore": 87,
    "tier": "B",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 23,
    "slug": "california-owts-impaired-areas",
    "name": "California OWTS Impaired Areas",
    "geography": "CA / impaired waters",
    "triggerType": "TRANSACTION_EVENT_TRIGGER",
    "triggerWindow": "Repair or replacement and impaired-water rules",
    "serviceIntents": "Septic engineering; installation",
    "researchScore": 86,
    "tier": "B",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 24,
    "slug": "hawaii-cesspool-trigger-events",
    "name": "Hawaii Cesspool Trigger Events",
    "geography": "HI",
    "triggerType": "TRANSACTION_EVENT_TRIGGER",
    "triggerWindow": "Modification, failure or pumping triggers; overlap with rank 16",
    "serviceIntents": "Wastewater engineering; septic; sewer",
    "researchScore": 86,
    "tier": "B",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  },
  {
    "rank": 25,
    "slug": "connecticut-underground-oil-tanks",
    "name": "Connecticut Underground Oil Tanks",
    "geography": "CT",
    "triggerType": "TRANSACTION_EVENT_TRIGGER",
    "triggerWindow": "Removal and contamination response; mandate unverified",
    "serviceIntents": "Tank removal; environmental remediation",
    "researchScore": 84,
    "tier": "B",
    "evidenceStatus": "UNVERIFIED",
    "publicationStatus": "RESEARCH_ONLY",
    "provenance": "USER_BRIEF_2026_09_26",
    "lastPrimarySourceVerifiedAt": null
  }
];
